/**
 * init-project.ts
 *
 * Initializes a .video-docs/ directory inside a client project.
 * Run this from the skill root, pointing at the client project directory.
 *
 * Usage:
 *   npx tsx scripts/init-project.ts /path/to/client-project
 *   npx tsx scripts/init-project.ts /home/user/projects/my-app
 *
 * Creates:
 *   <client>/.video-docs/
 *   <client>/.video-docs/config.json       ← fill in app_name, base_url, credentials
 *   <client>/.video-docs/flows/            ← place flow JSONs here
 *   <client>/.video-docs/output/           ← generated media (gitignored)
 *   <client>/.video-docs/output/.gitignore ← ignores everything inside output/
 *   <client>/.video-docs/docs/             ← React docs site (can be committed)
 *   <client>/.video-docs/README.md         ← regeneration instructions
 *
 * Also appends to <client>/.gitignore:
 *   .video-docs/output/
 */

import fs from 'fs';
import path from 'path';

const clientDir = process.argv[2];

if (!clientDir) {
  console.error('Usage: npx tsx scripts/init-project.ts <path-to-client-project>');
  console.error('Example: npx tsx scripts/init-project.ts /home/user/projects/my-app');
  process.exit(1);
}

const clientRoot = path.resolve(clientDir);
if (!fs.existsSync(clientRoot)) {
  console.error(`Directory not found: ${clientRoot}`);
  process.exit(1);
}

const videoDocsDir = path.join(clientRoot, '.video-docs');

if (fs.existsSync(videoDocsDir)) {
  console.log(`⚠  .video-docs/ already exists at: ${videoDocsDir}`);
  console.log('   Nothing to do. Delete it first if you want to reinitialize.');
  process.exit(0);
}

// ─── Create directory structure ───────────────────────────────────────────────

fs.mkdirSync(path.join(videoDocsDir, 'flows'),  { recursive: true });
fs.mkdirSync(path.join(videoDocsDir, 'output'), { recursive: true });
fs.mkdirSync(path.join(videoDocsDir, 'docs'),   { recursive: true });

// output/.gitignore — ignore all generated media (heavy files)
fs.writeFileSync(path.join(videoDocsDir, 'output', '.gitignore'), `# Generated by video-docs-builder — do not commit
*
!.gitignore
`);

// config.json template
fs.writeFileSync(path.join(videoDocsDir, 'config.json'), JSON.stringify({
  app_name: path.basename(clientRoot),
  base_url: 'http://localhost:3000',
  credentials: {
    demo: { email: 'admin@example.com', password: 'password' }
  },
  setup_login: { email: 'admin@example.com', password: 'password' },
}, null, 2) + '\n');

// README.md — regeneration instructions for future maintainers
const skillUrl = 'https://github.com/video-docs-builder/video-docs-builder';
fs.writeFileSync(path.join(videoDocsDir, 'README.md'), `# Video Documentation

Step-by-step tutorial videos for **${path.basename(clientRoot)}**.

> Made with [video-docs-builder](${skillUrl})

---

## Structure

\`\`\`
.video-docs/
├── config.json      ← app URL and credentials (keep private, add to .gitignore if needed)
├── flows/           ← recording scripts — commit these
├── output/          ← generated videos and audio — gitignored (heavy files)
└── docs/            ← React documentation site — commit or ignore as needed
\`\`\`

## Regenerate videos

### Install the skill
\`\`\`bash
npx skills add ${skillUrl}
\`\`\`

### Re-run a flow
From the skill directory (\`~/.claude/skills/video-docs-builder/\`):
\`\`\`bash
bash scripts/run-all.sh ${videoDocsDir}/flows/<flow>.json
\`\`\`

### Re-generate the docs site
\`\`\`bash
npx tsx scripts/generate-docs-site.ts ${videoDocsDir} --dev
\`\`\`

### Record a new section
\`\`\`bash
# Analyze the app first
npx tsx scripts/analyze-app.ts ${videoDocsDir}

# Then run the full pipeline for the new flow
bash scripts/run-all.sh ${videoDocsDir}/flows/<new-flow>.json
\`\`\`
`);

// ─── Update client .gitignore ─────────────────────────────────────────────────

const gitignorePath = path.join(clientRoot, '.gitignore');
const entry = '.video-docs/output/';

if (fs.existsSync(gitignorePath)) {
  const existing = fs.readFileSync(gitignorePath, 'utf-8');
  if (!existing.includes(entry)) {
    fs.appendFileSync(gitignorePath, `\n# video-docs-builder generated media (heavy files)\n${entry}\n`);
    console.log(`  ✓ Added "${entry}" to .gitignore`);
  } else {
    console.log(`  ℹ "${entry}" already in .gitignore`);
  }
} else {
  fs.writeFileSync(gitignorePath, `# video-docs-builder generated media (heavy files)\n${entry}\n`);
  console.log(`  ✓ Created .gitignore with "${entry}"`);
}

// ─── Done ─────────────────────────────────────────────────────────────────────

console.log(`
✅ Initialized .video-docs/ in: ${clientRoot}

Next steps:
  1. Edit .video-docs/config.json with your app URL and credentials
  2. From the skill directory, analyze your app:
     npx tsx scripts/analyze-app.ts ${videoDocsDir}
  3. Run the pipeline:
     bash scripts/run-all.sh ${videoDocsDir}/flows/<flow>.json
`);
